### ISSUE TITLE
gunicorn not starting automatically

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#127]
gunicorn appears to be not starting automatically in the development VM due to some path issues:

```
$ sudo tail -f /var/log/gunicorn/oo.log
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 196, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 291, in halt
    self.stop()
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 334, in stop
    self.reap_workers()
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 433, in reap_workers
    raise HaltServer(reason, self.APP_LOAD_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'App failed to load.' 4>
Failed to find application: 'app'

```

**Comment by redshiftzero** [comment]
No worries homie

**Comment by freddymartinez9** [comment]
Here is the error when I launch gunicorn from /vagrant/OpenOversight
```
root@vagrant-ubuntu-trusty-64:/vagrant/OpenOversight# gunicorn app:app &
[1] 30072
root@vagrant-ubuntu-trusty-64:/vagrant/OpenOversight# 2016-12-12 21:27:32 [30072] [INFO] Starting gunicorn 17.5
2016-12-12 21:27:32 [30072] [INFO] Listening at: http://127.0.0.1:8000 (30072)
2016-12-12 21:27:32 [30072] [INFO] Using worker: sync
2016-12-12 21:27:32 [30077] [INFO] Booting worker with pid: 30077
2016-12-12 21:27:32 [30077] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 473, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/base.py", line 115, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 33, in load
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/dist-packages/gunicorn/util.py", line 362, in import_app
    __import__(module)
  File "/vagrant/OpenOversight/app/__init__.py", line 1, in <module>
    from flask import Flask
ImportError: No module named flask
```

**Comment by redshiftzero** [comment]
(FYI this is not a blocker for development as one can manually run the server: 
`$ ~/oovirtenv/bin/python ./run.py`)

**Comment by freddymartinez9** [comment]
@redshiftzero I get the same error if I activate `virtualenv`
```
(venv) nginx@staging:~/oovirtenv/venv/OpenOversight/OpenOversight$ ls -F
app/  backup-2016-12-12.sql  config.pyc  db_repository/  downgrade_db.py  __init__.py  migrate_db.py  tests/  upgrade_db.py
(venv) nginx@staging:~/oovirtenv/venv/OpenOversight/OpenOversight$ gunicorn -b app:app &
[1] 27337
(venv) nginx@staging:~/oovirtenv/venv/OpenOversight/OpenOversight$ usage: gunicorn [OPTIONS] APP_MODULE
gunicorn: error: No application module specified.
q^C
[1]+  Exit 2                  gunicorn -b app:app
(venv) nginx@staging:~/oovirtenv/venv/OpenOversight$ python run.py 
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from OpenOversight.app import create_app, db
  File "/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/app/__init__.py", line 1, in <module>
    from flask import Flask
ImportError: No module named flask
```

**Comment by r4v5** [comment]
So, it has to do with the interaction between giving the gunicorn entrypoint as app:app and the refactoring that occurred in #126. Gunicorn is looking for app:app, and `OpenOversight/app/__init__.py` no longer creates an `app` for gunicorn to grab now that we're using flask factories. This is why the `run.py` approach works and `gunicorn -b app:app` dies.

This diff gets us part of the way there in that `app/__init__.py` now actually creates the thing if it's called:
```diff
diff --git a/OpenOversight/app/__init__.py b/OpenOversight/app/__init__.py
index 2768785..8c69ed1 100644
--- a/OpenOversight/app/__init__.py
+++ b/OpenOversight/app/__init__.py
@@ -1,10 +1,11 @@
 from flask import Flask
 from flask_sqlalchemy import SQLAlchemy
 from config import config
+from . import models
 
 db = SQLAlchemy()
 
-def create_app(config_name):
+def create_app(config_name='default'):
     app = Flask(__name__)
     app.config.from_object(config[config_name])
     config[config_name].init_app(app)
@@ -14,4 +15,6 @@ def create_app(config_name):
     from .main import main as main_blueprint
     app.register_blueprint(main_blueprint)
 
-    return app
\ No newline at end of file
+    return app
+
+app = create_app()
```

We're still getting this error, though:
```
Traceback (most recent call last):
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 473, in spawn_worker
    worker.init_process()
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 100, in init_process
    self.wsgi = self.app.wsgi()
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 115, in wsgi
    self.callable = self.load()
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 33, in load
    return util.import_app(self.app_uri)
  File "/home/vagrant/oovirtenv/local/lib/python2.7/site-packages/gunicorn/util.py", line 353, in import_app
    __import__(module)
  File "/vagrant/OpenOversight/app/__init__.py", line 4, in <module>
    from . import models
  File "/vagrant/OpenOversight/app/models.py", line 1, in <module>
    from . import db
ImportError: cannot import name db
```
There's something going on with the import chain required to get db there: there's no db.py, db is an object created in models.py.

**Comment by r4v5** [comment]
Also reasonably sure something is wrong in `app/utils.py`:
https://github.com/lucyparsons/OpenOversight/blob/develop/OpenOversight/app/utils.py#L10 probably shouldn't be instantiating a whole new app and db?

**Comment by r4v5** [comment]
#136 should fix this.

**Comment by r4v5** [comment]
(I disagree with the 'easy' label on this, btw :) )
