### ISSUE TITLE
Fix and document S3 key permissioning

### ISSUE THREAD

**Issue by r4v5** [lucyparsons/OpenOversight#191]
```
gunicorn[26747]: --------------------------------------------------------------------------------
gunicorn[26747]: ERROR in views [/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/app/main/views.py:305]:
gunicorn[26747]: Error uploading to S3: <class 'boto3.exceptions.S3UploadFailedError'> Failed to upload /tmp/tmpqbxYV_/c4c23bc6234d60d9f6f858e7b57230de9fd7206c8b89afc012f97b4267d7bd43.png to openoversight-staging/c4/c23bc6234d60d9f6f858e7b57230de9fd7206c8b89afc012f97b4267d7bd43.png: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied Traceback (most recent call last):
gunicorn[26747]:   File "/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/app/main/views.py", line 291, in submit_data
gunicorn[26747]:     new_filename)
gunicorn[26747]:   File "/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/app/utils.py", line 36, in upload_file
gunicorn[26747]:     ExtraArgs={'ACL': 'public-read'})
gunicorn[26747]:   File "/usr/local/lib/python2.7/dist-packages/boto3/s3/inject.py", line 106, in upload_file
gunicorn[26747]:     extra_args=ExtraArgs, callback=Callback)
gunicorn[26747]:   File "/usr/local/lib/python2.7/dist-packages/boto3/s3/transfer.py", line 283, in upload_file
gunicorn[26747]:     filename, '/'.join([bucket, key]), e))
gunicorn[26747]: S3UploadFailedError: Failed to upload /tmp/tmpqbxYV_/c4c23bc6234d60d9f6f858e7b57230de9fd7206c8b89afc012f97b4267d7bd43.png to openoversight-staging/c4/c23bc6234d60d9f6f858e7b57230de9fd7206c8b89afc012f97b4267d7bd43.png: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
gunicorn[26747]: --------------------------------------------------------------------------------
```
This is why S3 upload was failing; need to figure out why that PutObject failed.

**Comment by r4v5** [comment]
Ah, it needed a PutObjectAcl as well.
