### ISSUE TITLE
failed staging deploy due to migration issue

### ISSUE THREAD

**Issue by redshiftzero** [lucyparsons/OpenOversight#448]
Attempted to do a deployment from staging on `develop` (cf593a0) and had the following database migration issue: 

```
[staging.openoversight.lucyparsonslabs.com] run: su nginx -c "cd OpenOversight; /home/nginx/oovirtenv/venv/bin/python manage.py db upgrade"
[staging.openoversight.lucyparsonslabs.com] out: --------------------------------------------------------------------------------
[staging.openoversight.lucyparsonslabs.com] out: INFO in __init__ [/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/app/__init__.py:57]:
[staging.openoversight.lucyparsonslabs.com] out: OpenOversight startup
[staging.openoversight.lucyparsonslabs.com] out: --------------------------------------------------------------------------------
[staging.openoversight.lucyparsonslabs.com] out: INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
[staging.openoversight.lucyparsonslabs.com] out: INFO  [alembic.runtime.migration] Will assume transactional DDL.
[staging.openoversight.lucyparsonslabs.com] out: INFO  [alembic.runtime.migration] Running upgrade e14a1aa4b58f -> d86feb8fa5d1, empty message
[staging.openoversight.lucyparsonslabs.com] out: INFO  [alembic.runtime.migration] Running upgrade d86feb8fa5d1 -> 6065d7cdcbf8, empty message
[staging.openoversight.lucyparsonslabs.com] out: INFO  [alembic.runtime.migration] Running upgrade 6065d7cdcbf8 -> ca95c047bf42, empty message
[staging.openoversight.lucyparsonslabs.com] out: Traceback (most recent call last):
[staging.openoversight.lucyparsonslabs.com] out:   File "manage.py", line 94, in <module>
[staging.openoversight.lucyparsonslabs.com] out:     manager.run()
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
[staging.openoversight.lucyparsonslabs.com] out:     result = self.handle(argv[0], argv[1:])
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
[staging.openoversight.lucyparsonslabs.com] out:     res = handle(*args, **config)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
[staging.openoversight.lucyparsonslabs.com] out:     return self.run(*args, **kwargs)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
[staging.openoversight.lucyparsonslabs.com] out:     command.upgrade(config, revision, sql=sql, tag=tag)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
[staging.openoversight.lucyparsonslabs.com] out:     script.run_env()
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 425, in run_env
[staging.openoversight.lucyparsonslabs.com] out:     util.load_python_file(self.dir, 'env.py')
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
[staging.openoversight.lucyparsonslabs.com] out:     module = load_module_py(module_id, path)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
[staging.openoversight.lucyparsonslabs.com] out:     mod = imp.load_source(module_id, path, fp)
[staging.openoversight.lucyparsonslabs.com] out:   File "migrations/env.py", line 89, in <module>
[staging.openoversight.lucyparsonslabs.com] out:     run_migrations_online()
[staging.openoversight.lucyparsonslabs.com] out:   File "migrations/env.py", line 81, in run_migrations_online
[staging.openoversight.lucyparsonslabs.com] out:     context.run_migrations()
[staging.openoversight.lucyparsonslabs.com] out:   File "<string>", line 8, in run_migrations
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
[staging.openoversight.lucyparsonslabs.com] out:     self.get_context().run_migrations(**kw)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
[staging.openoversight.lucyparsonslabs.com] out:     step.migration_fn(**kw)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/OpenOversight/OpenOversight/migrations/versions/ca95c047bf42_.py", line 23, in upgrade
[staging.openoversight.lucyparsonslabs.com] out:     op.drop_index('ix_license_plates_non_state_identifier', table_name='license_plates')
[staging.openoversight.lucyparsonslabs.com] out:   File "<string>", line 8, in drop_index
[staging.openoversight.lucyparsonslabs.com] out:   File "<string>", line 3, in drop_index
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/operations/ops.py", line 964, in drop_index
[staging.openoversight.lucyparsonslabs.com] out:     return operations.invoke(op)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/operations/base.py", line 319, in invoke
[staging.openoversight.lucyparsonslabs.com] out:     return fn(self, operation)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/operations/toimpl.py", line 94, in drop_index
[staging.openoversight.lucyparsonslabs.com] out:     operation.to_index(operations.migration_context)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 209, in drop_index
[staging.openoversight.lucyparsonslabs.com] out:     self._exec(schema.DropIndex(index))
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
[staging.openoversight.lucyparsonslabs.com] out:     return conn.execute(construct, *multiparams, **params)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 945, in execute
[staging.openoversight.lucyparsonslabs.com] out:     return meth(self, multiparams, params)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
[staging.openoversight.lucyparsonslabs.com] out:     return connection._execute_ddl(self, multiparams, params)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
[staging.openoversight.lucyparsonslabs.com] out:     compiled
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
[staging.openoversight.lucyparsonslabs.com] out:     context)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
[staging.openoversight.lucyparsonslabs.com] out:     exc_info
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
[staging.openoversight.lucyparsonslabs.com] out:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
[staging.openoversight.lucyparsonslabs.com] out:     context)
[staging.openoversight.lucyparsonslabs.com] out:   File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
[staging.openoversight.lucyparsonslabs.com] out:     cursor.execute(statement, parameters)
[staging.openoversight.lucyparsonslabs.com] out: sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) index "ix_license_plates_non_state_identifier" does not exist
[staging.openoversight.lucyparsonslabs.com] out:  [SQL: '\nDROP INDEX ix_license_plates_non_state_identifier']
[staging.openoversight.lucyparsonslabs.com] out: 


Fatal error: run() received nonzero return code 1 while executing!

Requested: su nginx -c "cd OpenOversight; /home/nginx/oovirtenv/venv/bin/python manage.py db upgrade"
Executed: /bin/bash -l -c "cd /home/nginx/oovirtenv/venv/OpenOversight >/dev/null && su nginx -c \"cd OpenOversight; /home/nginx/oovirtenv/venv/bin/python manage.py db upgrade\""
```

**Comment by redshiftzero** [comment]
One can reproduce this locally by:

1. Provisioning a development VM on `master`
2. In the host (git isn't installed in the VM): `git checkout develop`
3. In the VM from `/vagrant/OpenOversight`: `pip install -r ../requirements.txt`
4. In the VM from `/vagrant/OpenOversight`: `python manage.py db upgrade`
