### ISSUE TITLE
Migrations in staging/prod seem broken

### ISSUE THREAD

**Issue by r4v5** [lucyparsons/OpenOversight#627]
```bash
(venv) nginx@staging:~/oovirtenv/venv/OpenOversight$ FLASK_APP=OpenOversight.app flask db upgrade
[2019-02-03 05:16:28,467] INFO in __init__: OpenOversight startup
Traceback (most recent call last):
  File "/home/nginx/oovirtenv/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask/cli.py", line 412, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask_migrate/cli.py", line 134, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/command.py", line 234, in upgrade
    script = ScriptDirectory.from_config(config)
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 134, in from_config
    timezone=config.get_main_option("timezone")
  File "/home/nginx/oovirtenv/venv/local/lib/python2.7/site-packages/alembic/script/base.py", line 60, in __init__
    "scripts folder." % dir)
alembic.util.exc.CommandError: Path doesn't exist: 'migrations'.  Please use the 'init' command to create a new scripts folder.
```
Wherever it's looking for a `migrations` path to be, it's not finding it. (the migrations exist at  `openoversight/OpenOversight/migrations`)

**Comment by dismantl** [comment]
By default `flask db` looks for the `migrations` directory relative to the working directory. So when it's run outside of the OpenOversight subdirectory, you need to specify the migrations path:
`FLASK_APP=OpenOversight.app flask db upgrade -d OpenOversight/migrations`

**Comment by r4v5** [comment]
Ah, alright. It seems to be ignoring the cwd. Adding the -d path worked, but it's now erroring out about the constraint that was in #612 already existing:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) constraint "fk_face_image_id" for relation "faces" already exists
 [SQL: 'ALTER TABLE faces ADD CONSTRAINT fk_face_image_id FOREIGN KEY(img_id) REFERENCES raw_images (id) ON DELETE CASCADE ON UPDATE CASCADE']
```

**Comment by dismantl** [comment]
Crap yeah I'm getting that in a dev environment too. Looks like the `fk_face_image_id` lines in the migration script were a mistake. I'll make a PR to remove that.

**Comment by r4v5** [comment]
Can you also add the path to migrations you referenced?
