### ISSUE TITLE
Issues due to new werkzeug version

### ISSUE THREAD

**Issue by brianmwaters** [lucyparsons/OpenOversight#699]
Werkzeug recently released version 1.0.0. When running `make create_db`, the following error is thrown:
```Traceback (most recent call last):
  File "../create_db.py", line 2, in <module>
    from OpenOversight.app import create_app
  File "/usr/src/app/OpenOversight/app/__init__.py", line 103, in <module>
    app = create_app()
  File "/usr/src/app/OpenOversight/app/__init__.py", line 40, in create_app
    from .main import main as main_blueprint  # noqa
  File "/usr/src/app/OpenOversight/app/main/__init__.py", line 5, in <module>
    from . import views  # noqa
  File "/usr/src/app/OpenOversight/app/main/views.py", line 25, in <module>
    from .forms import (FindOfficerForm, FindOfficerIDForm, AddUnitForm,
  File "/usr/src/app/OpenOversight/app/main/forms.py", line 1, in <module>
    from flask_wtf import FlaskForm as Form
  File "/ve/lib/python3.7/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/ve/lib/python3.7/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/ve/lib/python3.7/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/ve/lib/python3.7/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (/ve/lib/python3.7/site-packages/werkzeug/__init__.py)
make: *** [Makefile:16: create_db] Error 1
```

I've noticed similar issues with other Flask-based projects in recent weeks. The solution is either to pin to a version of werkzeug less than 1.0.0 (quick fix), or to look into what's actually changed in werkzeug and update our code (long-term fix).

**Comment by redshiftzero** [comment]
Looks like this issue is due to flask_wtf which updated this import in https://github.com/lepture/flask-wtf/pull/378, updating to Flask-WTF 0.14.3 should resolve (though there might be issues in other dependencies due to the changes in Werkzeug 1.0.0)

**Comment by brianmwaters** [comment]
Downgrading to werkzeug<1.0.0 (which in effect, today, gets us to werkzeug 0.16.1), also fixes it. However upgrading to the latest flask-wtf is definitely a better solution, if that works for me, I will submit a PR momentarily.
