### ISSUE TITLE
Internal Server Error while tagging

### ISSUE THREAD

**Issue by abandoned-prototype** [lucyparsons/OpenOversight#820]
When trying to tag a cop on either of these images: https://openoversight.com/cop_face/department/1/image/1548 and
https://openoversight.com/cop_face/department/1/image/1403 I get an 500 "Internal Server Error" once clicking "Add identified face". It doesn't seem to be related which officer is tagged in the image.

Could anyone with access to production reproduce the bug and then post the resulting error log? Thanks!

**Comment by r4v5** [comment]
```
Sep 01 04:47:00 openoversight gunicorn[11025]: [2020-09-01 04:47:00 +0000] [30076] [ERROR] Error handling request /cop_face/department/1/image/1403
Sep 01 04:47:00 openoversight gunicorn[11025]: Traceback (most recent call last):
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/PIL/Image.py", line 1930, in save
Sep 01 04:47:00 openoversight gunicorn[11025]:     format = EXTENSION[ext]
Sep 01 04:47:00 openoversight gunicorn[11025]: KeyError: ''
Sep 01 04:47:00 openoversight gunicorn[11025]: During handling of the above exception, another exception occurred:
Sep 01 04:47:00 openoversight gunicorn[11025]: Traceback (most recent call last):
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 135, in handle
Sep 01 04:47:00 openoversight gunicorn[11025]:     self.handle_request(listener, req, client, addr)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
Sep 01 04:47:00 openoversight gunicorn[11025]:     respiter = self.wsgi(environ, resp.start_response)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/app.py", line 2309, in __call__
Sep 01 04:47:00 openoversight gunicorn[11025]:     return self.wsgi_app(environ, start_response)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/app.py", line 2295, in wsgi_app
Sep 01 04:47:00 openoversight gunicorn[11025]:     response = self.handle_exception(e)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/app.py", line 1741, in handle_exception
Sep 01 04:47:00 openoversight gunicorn[11025]:     reraise(exc_type, exc_value, tb)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
Sep 01 04:47:00 openoversight gunicorn[11025]:     raise value
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
Sep 01 04:47:00 openoversight gunicorn[11025]:     response = self.full_dispatch_request()
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
Sep 01 04:47:00 openoversight gunicorn[11025]:     rv = self.handle_user_exception(e)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
Sep 01 04:47:00 openoversight gunicorn[11025]:     reraise(exc_type, exc_value, tb)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
Sep 01 04:47:00 openoversight gunicorn[11025]:     raise value
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
Sep 01 04:47:00 openoversight gunicorn[11025]:     rv = self.dispatch_request()
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
Sep 01 04:47:00 openoversight gunicorn[11025]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/flask_login/utils.py", line 261, in decorated_view
Sep 01 04:47:00 openoversight gunicorn[11025]:     return func(*args, **kwargs)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/OpenOversight/OpenOversight/app/main/views.py", line 775, in label_data
Sep 01 04:47:00 openoversight gunicorn[11025]:     cropped_image = crop_image(image, crop_data=(left, upper, right, lower), department_id=department_id)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/OpenOversight/OpenOversight/app/utils.py", line 498, in crop_image
Sep 01 04:47:00 openoversight gunicorn[11025]:     pimage.save(cropped_image_buf, image_type)
Sep 01 04:47:00 openoversight gunicorn[11025]:   File "/home/nginx/oovirtenv/lib/python3.5/site-packages/PIL/Image.py", line 1932, in save
Sep 01 04:47:00 openoversight gunicorn[11025]:     raise ValueError('unknown file extension: {}'.format(ext))
Sep 01 04:47:00 openoversight gunicorn[11025]: ValueError: unknown file extension:
```

**Comment by abandoned-prototype** [comment]
Thanks @r4v5, this was very helpful as I now know that this is covered by https://github.com/lucyparsons/OpenOversight/pull/807
